module.exports = {
  someSidebar: [
    {
      "Getting started": [
        "Getting Started/welcome",
        "Getting Started/install",
        "Getting Started/create-new-form",
      ],
    },
    {
      "Form Fields": [
        "Fields/fields-overview",
        "Fields/textfield",
        "Fields/multilinetextfield",
        "Fields/checkboxfield",
        "Fields/radiobuttonfield",
        "Fields/numberfield",
        "Fields/drop-downfield",
        "Fields/countryfield",
        "Fields/passwordfield",
        "Fields/emailfield",
        "Fields/urlfield",
        "Fields/fileuploadfield",
        "Fields/datefield",
        "Fields/timefield",
        "Fields/date-timefield",
        "Fields/monthfield",
        "Fields/colorpickerfield",
        "Fields/recaptchav2field",
        "Fields/decisionboxfield",
        "Fields/buttonfield",
        "Fields/paypalfield",
        "Fields/razorpayfield",
      ],
    },
    {
      "Style Editor": [
        "StyleEditor/background-customize",
        "StyleEditor/form-customize",
        "StyleEditor/form-block-customize",
        "StyleEditor/field-customize",
      ],
    },
    "Response Management/response-management",
    "form-settings",
    "conditional-logic",
    "confirmation-massage",
    "email-template",
    {
      Integrations: [
        "Integrations/pods",
        "Integrations/acf",
        "Integrations/metabox",
        "Integrations/googlesheet",
        "Integrations/googleads",
        "Integrations/telegram",
        "Integrations/activecampaign",
        "Integrations/mailchimp",
        "Integrations/mailpoet",
        "Integrations/encharge",
        "Integrations/sendinblue",
        "Integrations/fluentcrm",
        "Integrations/customposttype",
        "Integrations/recaptchav3",
        "Integrations/zapier",
        "Integrations/pabbly",
        "Integrations/integromat",
        "Integrations/integrately",
        "Integrations/zoho-flow",
        "Integrations/zoho-analytics",
        "Integrations/zoho-crm",
        "Integrations/zoho-recruit",
        "Integrations/zoho-workdrive",
        "Integrations/zoho-desk",
        "Integrations/zoho-campaign",
        "Integrations/zoho-mail",
        "Integrations/zoho-project",
        "Integrations/zoho-sheet",
        "Integrations/zoho-sign",
        "Integrations/zoho-creator",
        "Integrations/zoho-bigin",
      ],
    },
    "api",
    {
      Others: [
        "Others/prevent-bot",
        "Others/get-url-parameter",
        "Others/email-autoresponder",
      ],
    },
  ],
  changelog: [
    "changelog/overview",
    // { "Log Details": ["changelog/1.3", "changelog/1.4"] },
  ],
};
